#!/usr/bin/env bash

set -eux

case "$0" in
  *neovim* )
    vimpackdir="$HOME/.config/nvim/pack"
    vimcmd="nvim"
    ;;
  * )
    vimpackdir="$HOME/.vim/pack"
    vimcmd="vim"
    ;;
esac

if ! command -v "$vimcmd" 2>&1 /dev/null ; then
  echo "Please install '$vimcmd' before running this update script."
  exit 1
fi

optdir="$vimpackdir/minpac/opt"
minpacdir="$optdir/minpac"
minpacrepo="https://github.com/k-takata/minpac.git"

mkdir -p "$optdir"

[ -d "$minpacdir" ] || git clone "$minpacrepo" "$minpacdir"

"$vimcmd" +PackUpdate
