add_newline = false

format = """
$env_var\
${custom.pre}\
$username\
$hostname\
$shlvl\
$singularity\
$kubernetes\
$directory\
${custom.post}\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$cobol\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

[custom.pre]
when = "true"
style = "bold green"
symbol = '\['
format = "[$symbol]($style)"

[username]
show_always = true
format = "[$user]($style)@"

[hostname]
ssh_only = false

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"

[custom.post]
when = "true"
style = "bold green"
symbol = '\]'
format = "[$symbol]($style) "

[env_var.TOOLBOX_NAME_ENV]
variable = "TOOLBOX_NAME_ENV"
symbol = "⬢"
default = "no toolbox"
style = "bold purple"
format = "[$symbol ($env_value)]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✗❯](bold red)"
